### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by JeserLeonel** [SistemasTecTlaxiaco/infografia-JeserLeonel#2]
![110549227-5ec24700-80f7-11eb-8b53-68287bc72383](https://user-images.githubusercontent.com/79876847/112063148-9208cb00-8b26-11eb-8706-2239c725121a.png)

**Comment by IvanMc98** [comment]
Cumple con todos los criterios
**Calificación: 20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
